version = '0.1.1'

[[files."CHANGELOG.md"]]
search = '''
## [Unreleased]
'''
replace = '''
## [Unreleased]

## [{{new_version}}] - {{utcnow | strftime('%Y-%m-%d')}}
'''

[[files."CHANGELOG.md"]]
search = '''
[Unreleased]: https://github.com/dochang/elpa-clone/compare/{{old_version}}...HEAD
'''
replace = '''
[Unreleased]: https://github.com/dochang/elpa-clone/compare/{{new_version}}...HEAD
[{{new_version}}]: https://github.com/dochang/elpa-clone/compare/{{old_version}}...{{new_version}}
'''

[[files."elpa-clone.el"]]
search = '{{old_version}}'
replace = '{{new_version}}'

[[files."README.md"]]
search = '{{old_version}}'
replace = '{{new_version}}'
