---
{
   "kind": "pipeline",
   "name": "test-emacs24",
   "steps": [
      {
         "commands": [
            "apt-get update && apt-get --yes install curl rsync",
            "cask install",
            "cask exec ert-runner"
         ],
         "environment": {
            "TARGET_ROOT": "/tmp/elpa-clone/emacs24"
         },
         "image": "silex/emacs:24-ci-cask",
         "name": "test"
      }
   ],
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "test-emacs25",
   "steps": [
      {
         "commands": [
            "apt-get update && apt-get --yes install curl rsync",
            "cask install",
            "cask exec ert-runner"
         ],
         "environment": {
            "TARGET_ROOT": "/tmp/elpa-clone/emacs25"
         },
         "image": "silex/emacs:25-ci-cask",
         "name": "test"
      }
   ],
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "test-emacs26",
   "steps": [
      {
         "commands": [
            "apt-get update && apt-get --yes install curl rsync",
            "cask install",
            "cask exec ert-runner"
         ],
         "environment": {
            "TARGET_ROOT": "/tmp/elpa-clone/emacs26"
         },
         "image": "silex/emacs:26-ci-cask",
         "name": "test"
      }
   ],
   "type": "docker"
}
...
